/** Fuseaux horaires courants pour les familles expatriées AEFE */
export const COMMON_TIMEZONES = [
  { value: "Europe/Paris", label: "Europe/Paris (France, Belgique, Suisse…)" },
  { value: "Europe/London", label: "Europe/London (Royaume-Uni)" },
  { value: "Europe/Berlin", label: "Europe/Berlin (Allemagne)" },
  { value: "Europe/Madrid", label: "Europe/Madrid (Espagne)" },
  { value: "Europe/Rome", label: "Europe/Rome (Italie)" },
  { value: "Europe/Lisbon", label: "Europe/Lisbon (Portugal)" },
  { value: "Africa/Casablanca", label: "Africa/Casablanca (Maroc)" },
  { value: "Africa/Tunis", label: "Africa/Tunis (Tunisie)" },
  { value: "Africa/Algiers", label: "Africa/Algiers (Algérie)" },
  { value: "Africa/Cairo", label: "Africa/Cairo (Égypte)" },
  { value: "Africa/Dakar", label: "Africa/Dakar (Sénégal)" },
  { value: "Africa/Abidjan", label: "Africa/Abidjan (Côte d'Ivoire)" },
  { value: "Africa/Douala", label: "Africa/Douala (Cameroun)" },
  { value: "Asia/Dubai", label: "Asia/Dubai (Émirats arabes unis)" },
  { value: "Asia/Riyadh", label: "Asia/Riyadh (Arabie Saoudite)" },
  { value: "Asia/Qatar", label: "Asia/Qatar (Qatar)" },
  { value: "Asia/Tokyo", label: "Asia/Tokyo (Japon)" },
  { value: "Asia/Singapore", label: "Asia/Singapore (Singapour)" },
  { value: "Asia/Hong_Kong", label: "Asia/Hong_Kong (Hong Kong)" },
  { value: "Asia/Shanghai", label: "Asia/Shanghai (Chine)" },
  { value: "Asia/Kolkata", label: "Asia/Kolkata (Inde)" },
  { value: "America/New_York", label: "America/New_York (Est USA)" },
  { value: "America/Los_Angeles", label: "America/Los_Angeles (Ouest USA)" },
  { value: "America/Toronto", label: "America/Toronto (Canada Est)" },
  { value: "America/Sao_Paulo", label: "America/Sao_Paulo (Brésil)" },
  { value: "America/Mexico_City", label: "America/Mexico_City (Mexique)" },
  { value: "America/Argentina/Buenos_Aires", label: "America/Argentina/Buenos_Aires (Argentine)" },
] as const;
